### ISSUE TITLE
GoogleCode Mp4Parser 1.0.5.6 not available in sonos staging repo, cannot compile fragencrypter.

### ISSUE THREAD

**Issue by nwind21** [castlabs/dashencrypt#19]
<groupId>com.googlecode.mp4parser</groupId>
            <artifactId>isoparser</artifactId>
            <version>1.0.5.6</version>

I'm assuming the 1.0.5.6 is being resolved from this repository as specified in the pom:
https://oss.sonatype.org/content/repositories/comgooglecodemp4parser-1055

This repository doesn't resolve though and I can't complete the build of the fragencrypter.  Can someone verify the repository path and version?

**Comment by sannies** [comment]
In deed, it's no longer there. No clue what happened, perhaps I dropped it by accident. I'll make sure that this works on Monday - until then please checkout mp4parser https://github.com/sannies/mp4parser  tag: "mp4parser-project-1.0.5.6-5" and mvn install it on your machine.

**Comment by nwind21** [comment]
Cool, just tried and the workaround is ok.  I'll check back later next week.  Thanks.

**Comment by sannies** [comment]
i bumped to 1.0.5.7 and this is available
