### ISSUE TITLE
Audio output cannot be played in chrome

### ISSUE THREAD

**Issue by atomerz** [castlabs/dashencrypt#23]
I tried to DASH a video file by following the steps described in the wiki. However I cannot play the video in my browser (Chrome version 43) using [dash.js](http://cdn.dashjs.org/latest/dash.all.js) player. I get error `MEDIA_ERR_SRC_NOT_SUPPORTED`. After looking around a bit I noticed that the audio output of dashencrypt has the codec `mp4a.40.5` (the samples on internet use codec `mp4a.40.2` and I can play them). I then tried to DASH the video representations only and everything worked fine i.e. I can play it in my browser.  
How can I correctly DASH the audio representation into `mp4a.40.2`?

**Comment by chartelt** [comment]
Hi,
{{mp4a.40.2}} = AAC-LC ; {{mp4a.40.5}} = AAC-HE
Use different audio encoding, or make sure to have explicit signalling when muxing AAC-HE into MP4. Chrome supports 40.5. With MP4Box setting flag  "-sbrx" during muxing for example will create MP4 files which get packaged correctly.
